### ISSUE TITLE
Support siva files bigger than 2GB

### ISSUE THREAD

**Issue by smacker** [src-d/siva-java#18]
Siva reader uses MappedByteBuffer:
https://github.com/src-d/siva-java/blob/master/src/main/java/tech/sourced/siva/SivaReader.java#L43

And there is a limit in jdk https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/nio/ch/FileChannelImpl.java#L788

Exception using siva-java with engine:
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 415 in stage 1.0 failed 4 times, most recent failure: Lost task 415.3 in stage 1.0 (TID 1072, 10.2.15.79, executor 8): java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:869)
	at tech.sourced.siva.SivaReader.getEntry(SivaReader.java:42)
	at tech.sourced.engine.provider.RepositoryObjectFactory$$anonfun$genSivaRepository$1.apply(RepositoryProvider.scala:209)
```

Go implementation can process big files just fine:
```
$ ls -lah
-rw-r--r--. 1 root root 4.6G Jan  5 09:48 ec644e00e3cab40629bc32562269c011ec2a6b14.siva
$ siva unpack ec644e00e3cab40629bc32562269c011ec2a6b14.siva
$ ls
HEAD  config  ec644e00e3cab40629bc32562269c011ec2a6b14.siva  go  objects  refs
```

Big files are available in `/apps/borges/too-big` on HDFS if you need them.

**Comment by ajnavarro** [comment]
Spark has the same problem: https://issues.apache.org/jira/browse/SPARK-6190

We can follow that link to figure out witch solution they find, Using better implementation of MappedByteBuffer, per example.

**Comment by ajnavarro** [comment]
Also relevant: https://bugs.java.com/view_bug.do?bug_id=6347833

**Comment by smacker** [comment]
If we are talking about Spark there is an umbrella issue about 2GB limit: https://issues.apache.org/jira/browse/SPARK-6235
JFYI

**Comment by bzz** [comment]
I might be wrong, but when this is fixed, we might not hit the above-mentioned Spark limitation. 

AFAIK jgit will be dealing with reading the unpacked files in RepositoryProvider, so 2Gb does not hit Spark that way.

Another argument for fixing siva-java impl is that go iml can do that.

**Comment by bzz** [comment]
@smaker could  you please either post a Siva filename that triggered this or a path to such a file that triggers this failure in HDFS as well?

AFAIK it has to be not just >2Gb Siva file, but the one that has >2Gb in single file inside.

**Comment by smacker** [comment]
I don't know which one caused the problem. 
Error messages were improved in engine 0.3.5 but it isn't available yet.

There are few files in staging HDFS in folder `/apps/borges/too-big`.
With engine 0.3.4 it looks like this:
```
scala> import tech.sourced.engine._
import tech.sourced.engine._

scala> val engine = Engine(spark, "hdfs://hdfs-namenode/apps/borges/too-big", "siva")
engine: tech.sourced.engine.Engine = tech.sourced.engine.Engine@7ddd5715

scala> engine.getRepositories.show()
18/01/12 09:56:31 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 10.2.36.11, executor 1): java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
```

**Comment by ajnavarro** [comment]
PR: https://github.com/src-d/siva-java/pull/20

**Comment by bzz** [comment]
@ajnavarro so cool! Can't wait for a v0.1.3 and a new release of Engine that will use a new version :)
@smacker thank you for reproducible example!

Would be happy to test it with a new Engine version.

**Comment by erizocosmico** [comment]
v0.1.3 released.

**Comment by bzz** [comment]
With engine 0.3.6 version including this lib, was able to verify that this issue is fixed! 🎉
