### ISSUE TITLE
blobs siva content access

### ISSUE THREAD

**Issue by sakalouski** [src-d/siva-java#24]
Hi, 
I am very new to java and trying to use it to access blobs content of siva files. Is there an easy way of doing it? Tests seem to have something similar, but in Scala - it is quite confusing. 
Thank You!

**Comment by erizocosmico** [comment]
Hi! By blobs content do you mean the contents of the siva files themselves or do you mean the blobs of git repositories stored as siva files?

**Comment by sakalouski** [comment]
I mean blobs of git repositories - I have downloaded Public GitHub Archive and want to unpack it.
I have tried using jigit connector and engine, but the solution is not stable. So, want to simply unpack it in a minimalistic way.

**Comment by erizocosmico** [comment]
Siva is just an archiver format, so it does not have any capabilities related to git other than storing files inside. You can unpack a siva file with the example in the README: https://github.com/src-d/siva-java#example-of-usage. But for reading as a git repository, you will have to use something like [jgit](https://github.com/eclipse/jgit) once it's unpacked.

**Comment by sakalouski** [comment]
Thank You, got it
